### ISSUE TITLE
How to change the possible values of a parameter?

### ISSUE THREAD

**Issue by bluestyle97** [threedle/GeoCode#14]
I'm not very familiar with the geometry nodes of blender. If I want to change the minimum number of cross rails (cr_count) from 3 to 2, how can I do that? Could you please give me some instructions?

**Comment by ofekp** [comment]
Sure!

Open the shape program you want to change the min/max values in.
Go to the Geometry Nodes workspace tab (top of the window)
![image](https://user-images.githubusercontent.com/9001738/230793146-45de46fc-deea-47bb-97ec-6525a517b582.png)
Hopefully, you can now see the geometry nodes editor, it looks something like this (copped):
![image](https://user-images.githubusercontent.com/9001738/230793195-e8e7840a-301d-436d-8baa-930041800e4c.png)
Hover your mouse so it is within that window and press `n`
You should now see a sidebar
![image](https://user-images.githubusercontent.com/9001738/230793233-baca1009-5810-46e4-86cc-66c4af9df92a.png)
Click the `Group` tab in that sidebar
You can now select the input parameters and change the min/max and default values
![image](https://user-images.githubusercontent.com/9001738/230793294-2131b92e-39a5-488e-aa24-eeb5752cc602.png)

Please be aware that changing these values might affect the validity of the shapes.
I hope this helps.

**Comment by bluestyle97** [comment]
Wow, this is so helpful! Thanks a lot!
