### ISSUE TITLE
Resolve package not found even after adding under pip 

### ISSUE THREAD

**Issue by ManishJu** [threedle/GeoCode#5]
How to resolve this issue ? :

ResolvePackageNotFound:
  - nvidiacub=1.10.0
  - pytorch3d

**Comment by ofekp** [comment]
Both packages are in the environment.yml file and should have been installed, please check if you have any errors during the installation of a new conda environment and attach them here.

**Comment by ManishJu** [comment]
![image](https://user-images.githubusercontent.com/24234466/209441986-92014e46-912c-4a5a-8b9f-2c339d010e30.png)

**Comment by ManishJu** [comment]
I can see the 2 packages, even tried to add them below pip...no success

**Comment by ofekp** [comment]
Do you have a GPU in your system? If so, can you please share what you see when you execute `nvidia-smi`?

**Comment by itailang** [comment]
Dear @ManishJu,

Closing the issue for now. If you have further questions, feel free to reach out. Thanks!

**Comment by ManishJu** [comment]
![image](https://user-images.githubusercontent.com/24234466/209796397-17169028-dfb0-4576-b056-9c476a1fd1ab.png)

**Comment by ManishJu** [comment]
First I tried running the project on windows . It failed due to Path issues . I gave up fixing that and tried to do it in WSL for Wndows.
WSL for windows 10  21H is not fully functional and has lots of bugs. 
FInally I updated my old LInux partition and was able to run the project.  :)
I will try to generate again on windows and push fixes in future...

**Comment by itailang** [comment]
Thanks for sharing, @ManishJu!
An update about running on Windows would be great. Please let us know when relevant.
