### ISSUE TITLE
Generating Data for a New Category (like beds)

### ISSUE THREAD

**Issue by abbhinavvenkat** [threedle/GeoCode#9]
Hi, 

Thanks for sharing GeoCode! 

I want to learn a parametric representation of a new category (like bed frames). My understanding of the steps to follow are - 
a. Decide on the parameters and create a geometry node in blender with it. 
b. Use this blender file to generate objs and sketches with the given dataset_generator.py and sketch_generator.py
c. Train the model using this data. 

I wanted to clarify if  - 
1. The above workflow is correct, and 
2. If we have to manually create the geometry nodes each time we want to do it for a new category (or do you have any suggestions here?)

Thanks, 
Abbhinav

**Comment by ofekp** [comment]
Your workflow is indeed correct :)
You will have to create the program for the beds. You can use some of the logic already in the chair and table programs as these share geometric features with the domain you intend to work on.

**Comment by abbhinavvenkat** [comment]
Thanks for your suggestion!

**Comment by vrk7** [comment]
@abbhinavvenkat Did you happen to achieve the same with the mentioned new category?

**Comment by ofekp** [comment]
@vrk7 https://github.com/threedle/GeoCode/issues/15#issuecomment-1763496673
